---
driver:
  name: ec2
  aws_ssh_key_id: # Add your key here
  instance_type: t2.micro
  security_group_ids: # Add your security group here ["sg-xxxxxxx"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    attributes:
